//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.LibroServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LibroServiceReference.ILibroService")]
    public interface ILibroService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/GetAll", ReplyAction="http://tempuri.org/ILibroService/GetAllResponse")]
        SL.Libro[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/GetAll", ReplyAction="http://tempuri.org/ILibroService/GetAllResponse")]
        System.Threading.Tasks.Task<SL.Libro[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/Add", ReplyAction="http://tempuri.org/ILibroService/AddResponse")]
        bool Add(SL.Libro obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/Add", ReplyAction="http://tempuri.org/ILibroService/AddResponse")]
        System.Threading.Tasks.Task<bool> AddAsync(SL.Libro obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/GetById", ReplyAction="http://tempuri.org/ILibroService/GetByIdResponse")]
        SL.Libro GetById(int idLibro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/GetById", ReplyAction="http://tempuri.org/ILibroService/GetByIdResponse")]
        System.Threading.Tasks.Task<SL.Libro> GetByIdAsync(int idLibro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/Update", ReplyAction="http://tempuri.org/ILibroService/UpdateResponse")]
        bool Update(SL.Libro obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/Update", ReplyAction="http://tempuri.org/ILibroService/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(SL.Libro obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/Delete", ReplyAction="http://tempuri.org/ILibroService/DeleteResponse")]
        bool Delete(int idLibro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/Delete", ReplyAction="http://tempuri.org/ILibroService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int idLibro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibroServiceChannel : PL.LibroServiceReference.ILibroService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibroServiceClient : System.ServiceModel.ClientBase<PL.LibroServiceReference.ILibroService>, PL.LibroServiceReference.ILibroService {
        
        public LibroServiceClient() {
        }
        
        public LibroServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibroServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibroServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibroServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SL.Libro[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<SL.Libro[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public bool Add(SL.Libro obj) {
            return base.Channel.Add(obj);
        }
        
        public System.Threading.Tasks.Task<bool> AddAsync(SL.Libro obj) {
            return base.Channel.AddAsync(obj);
        }
        
        public SL.Libro GetById(int idLibro) {
            return base.Channel.GetById(idLibro);
        }
        
        public System.Threading.Tasks.Task<SL.Libro> GetByIdAsync(int idLibro) {
            return base.Channel.GetByIdAsync(idLibro);
        }
        
        public bool Update(SL.Libro obj) {
            return base.Channel.Update(obj);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(SL.Libro obj) {
            return base.Channel.UpdateAsync(obj);
        }
        
        public bool Delete(int idLibro) {
            return base.Channel.Delete(idLibro);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int idLibro) {
            return base.Channel.DeleteAsync(idLibro);
        }
    }
}
